#!/bin/sh
# description: SoftEther VPN Server
### BEGIN INIT INFO
# Provides:          vpnserver
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: softether vpnserver
# Description:       softether vpnserver daemon
### END INIT INFO
DAEMON=/usr/local/softether-vpn-server/vpnserver
LOCK=/var/lock/subsys/vpnserver
test -x $DAEMON || exit 0
case "$1" in
start)
$DAEMON start
touch $LOCK
sleep 3
ip addr add 192.168.19.2/24 dev vpn_vpn
;;
stop)
ip addr del 192.168.19.2/24 dev vpn_vpn
$DAEMON stop
rm $LOCK
;;
restart)
ip addr del 192.168.19.2/24 dev vpn_vpn
$DAEMON stop
sleep 3
$DAEMON start
sleep 3
ip addr add 192.168.19.2/24 dev vpn_vpn
;;
status)
/usr/local/softether-vpnclient/vpncmd localhost /client /cmd accountstatusget alma.sb.sace.ro
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit 0
